site_name: Python Practice Projects
site_description: Beginner-friendly Python projects for learning by building
site_author: Python Practice Community
site_url: https://i-invincib1e.github.io/Here-i-come-Python/

repo_name: I-invincib1e/Here-i-come-Python
repo_url: https://github.com/I-invincib1e/Here-i-come-Python

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
      - Overview: docs/overview.md
      - Learning Path: docs/LEARNING_PATH.md
      - Contributing Guide: docs/CONTRIBUTING_GUIDE.md
  - Projects:
      - Level 1 (Beginners):
          - Overview: level1/README.md
          - Calculator CLI: level1/calculator_cli/README.md
          - Guess Number: level1/guess_number/README.md
          - Rock Paper Scissors: level1/rock_paper_scissors/README.md
          - Stopwatch CLI: level1/stopwatch_cli/README.md
          - Todo CLI: level1/todo_cli/README.md
      - Level 2 (Intermediate):
          - Overview: level2/README.md
          - Expense Tracker: level2/expense_tracker/README.md
          - File Organizer: level2/file_organizer/README.md
          - Markdown Notes: level2/md_notes/README.md
          - Quiz Game: level2/quiz_game/README.md
          - Tic Tac Toe AI: level2/tictactoe_ai/README.md
  - DSA Track:
      - Overview: dsa/README.md
      - Arrays: dsa/arrays.md
      - Strings: dsa/strings.md
      - Hash Maps: dsa/hash_maps.md
      - Stacks & Queues: dsa/stacks_queues.md
      - Recursion: dsa/recursion.md
  - Community:
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Good First Issues: docs/GOOD_FIRST_ISSUES.md
      - Contributors: CONTRIBUTORS.md
  - Development:
      - Roadmap: ROADMAP.md
      - License: LICENSE
